import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../../utils/trpc";

const Home: NextPage = () => {
  const { data: compositions } = trpc.useQuery(["compositions.getAll"]);

  return (
    <>
      <Head>
        <title>Compositions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Compositions</h1>
        <ul>
          {compositions?.map((composition) => {
            return (
              <li
                style={{
                  border: "1px solid black",
                }}
                key={composition.id}
              >
                <Link href={`/explore/${composition.id}`} passHref>
                  <a>
                    <h3>{composition.name}</h3>
                  </a>
                </Link>
                <p>{composition.description}</p>
                {composition.tracks.length > 0 && (
                  <>
                    <h4>Tracks in composition:</h4>
                    {composition.tracks.map((track, idx) => {
                      return (
                        <ul
                          style={{
                            border: "1px solid black",
                          }}
                          key={track.name + idx}
                        >
                          <li>{track.name}</li>
                        </ul>
                      );
                    })}
                  </>
                )}
              </li>
            );
          })}
        </ul>
      </div>
    </>
  );
};

export default Home;
